spring:
  application:
    name: car-management
  graphql:
    websocket:
      path: /graphql
    graphiql:
      enabled: true
    path: /graphql
  messages:
    basename: validation
  datasource:
    url: jdbc:postgresql://localhost:5432/car_management
    username: admin
    password: 999
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
