spring:
  application:
    name: car-management
  datasource:
    url: jdbc:postgresql://localhost:5432/car_management
    username: ${DATABASE_USER:username}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      # for debug
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
